# Screen data
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50

# Map data
MAP_WIDTH = 80
MAP_HEIGHT = 43


# Room data
ROOM_MAX_SIZE = 10
ROOM_MIN_SIZE = 6
ROOM_MAX_ROOMS = 30
ROOM_MAX_MONSTERS_PER_ROOM = 2
ROOM_MAX_ITEMS_PER_ROOM = 2